name: clean nojekyll

on:
  workflow_run:
    workflows: ["github pages"]
    types:
      - completed

jobs:
  clean:
    runs-on: ubuntu-20.04
    steps:
      - name: clean
        run: rm -f .nojekyll