name: github pages

on:
  push:
    branches:
      - main
      - gh-pages
  pull_request:
    branches:
      - gh-pages

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: cd slides && hugo --gc --minify --cleanDestinationDir -d public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./slides/public

  clean:
    if: github.ref == 'refs/heads/gh-pages'
    runs-on: ubuntu-20.04
    steps:
      - name: clean
        run: rm -f .nojekyll